### ISSUE TITLE
Release 1.0.0 doesn't include bunldex.exs file

### ISSUE THREAD

**Issue by Rados13** [kim-company/video_mixer#1]
Release 1.0.0 doesn't include `bunldex.exs` file, which leads to errors during the compilation of the project:
```
==> video_mixer
could not compile dependency :video_mixer, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile video_mixer", update it with "mix deps.update video_mixer" or clean it with "mix deps.clean video_mixer"
** (Code.LoadError) could not load /Users/radoslawszuma/dev/membrane_live/deps/video_mixer/bundlex.exs. Reason: enoent
    (elixir 1.14.0) lib/code.ex:1807: Code.find_file!/2
    (elixir 1.14.0) lib/code.ex:1237: Code.require_file/2
    (bundlex 1.0.1) lib/bundlex/project.ex:162: Bundlex.Project.load/1
    (bundlex 1.0.1) lib/bundlex/project.ex:141: Bundlex.Project.get/1
    (bundlex 1.0.1) lib/tasks/compile.bundlex.ex:29: Mix.Tasks.Compile.Bundlex.run/1
    (mix 1.14.0) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
```

**Comment by philipgiuliani** [comment]
I've just released v1.0.1 which includes the `bundlex.exs` file. Thanks!
